server:
  port: 9002
spring:
  application:
    name: nacos-payment-provider
  cloud:
    nacos:
      discovery:
        server-addr: 172.20.215.232:8001 #配置Nacos地址 nacos集群
#        server-addr: 172.20.215.232:8848 #配置Nacos地址
management:
  endpoints:
    web:
      exposure:
        include: "*"