server:
  port: 80

spring:
  application:
    name: hystrixorder80
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka
feign:
  hystrix:
    enabled: true
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 5000

ribbon:
  ReadTimeout: 5000
  ConnectTimeout: 5000


#      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka