server:
  port: 7001
eureka:
  instance:
    hostname: eureka7001.com #eureka服务器的实例名称
  client:
    #表示不向Eureka注册中心注册自己
    register-with-eureka: false
    #表示自己就是注册中心，我的职责就是维护实例而不是检索服务
    fetch-registry: false

    service-url:
      #设置Eureka Server交互的查询服务和注册服务都需要依赖这个地址
#      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
      #集群指向其他Eureka Server
#      defaultZone: http://eureka7002.com:7002/eureka/
      #单机指向自己
      defaultZone: http://eureka7001.com:7002/eureka/
  server:
    #关闭自我保护，服务不可用会被 剔除
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 2000

