server:
  port: 8401
spring:
  application:
    name: cloudalibaba-sentinel-service
  cloud:
    nacos:
      discovery:
        server-addr: 172.20.215.232:8848 #配置Nacos地址
    sentinel:
      transport:
        dashboard: 172.20.215.232:8858
        port: 8719
management:
  endpoints:
    web:
      exposure:
        include: "*"